# Generated by Django 3.2.11 on 2022-01-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('isImportant', models.BooleanField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('createdTime', models.DateTimeField()),
            ],
            options={
                'ordering': ['createdTime'],
            },
        ),
    ]
