# Generated by Django 3.2.11 on 2022-01-18 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('theBorrower', models.TextField()),
                ('borrowerType', models.TextField(choices=[('Karyawan', 'Karyawan'), ('Non-Karyawan', 'Non-Karyawan')])),
                ('nominal', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_borrowed', models.DateField(default=datetime.date.today)),
                ('time_borrowed', models.TimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
