# Generated by Django 3.2.11 on 2022-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_borrowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_borrowed',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
